# Generated by Django 3.0.2 on 2020-03-04 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCodes',
            fields=[
                ('company_name', models.CharField(max_length=100)),
                ('company_trade_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('currency', models.CharField(max_length=5)),
                ('value_in_usd', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='DerivativeTrades',
            fields=[
                ('date', models.DateTimeField(verbose_name='date of trade')),
                ('trade_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('notional_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('notional_currency', models.CharField(max_length=5)),
                ('quantity', models.IntegerField()),
                ('maturity_date', models.DateTimeField(verbose_name='maturity date')),
                ('underlying_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('underlying_currency', models.CharField(max_length=5)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buying_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying', to='system.CompanyCodes')),
                ('selling_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling', to='system.CompanyCodes')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField()),
                ('rule_desc', models.CharField(max_length=200)),
                ('rule_edition', models.CharField(max_length=10)),
                ('rule_typing', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.CompanyCodes')),
            ],
        ),
        migrations.CreateModel(
            name='Removals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSellers',
            fields=[
                ('product_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.CompanyCodes')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.ProductSellers')),
            ],
        ),
        migrations.CreateModel(
            name='Insertions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.DerivativeTrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Edits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('field', models.CharField(max_length=30)),
                ('old_value', models.CharField(max_length=100)),
                ('new_value', models.CharField(max_length=100)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.DerivativeTrades')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('average', models.DecimalField(decimal_places=4, max_digits=20)),
                ('standard_dev', models.DecimalField(decimal_places=4, max_digits=20)),
                ('prod_count', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.CompanyCodes')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
