# Generated by Django 3.0.3 on 2020-03-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='rule_typing',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
