# Generated by Django 3.0.3 on 2020-03-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rules_rule_typing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
