# Generated by Django 3.0.3 on 2020-03-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_delete_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.IntegerField()),
                ('rule_desc', models.CharField(max_length=200)),
                ('rule_edition', models.CharField(max_length=10)),
                ('rule_typing', models.CharField(max_length=10)),
            ],
        ),
    ]
